# Generated by Django 4.2.4 on 2023-09-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1860)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
